CREATE TABLE AMB_PERMISSOES (
  ID_PERMISSAO AUTOINCREMENT PRIMARY KEY,
  PERFIL TEXT(50) NOT NULL,
  PERMISSAO TEXT(100) NOT NULL,
  ATIVO YESNO DEFAULT TRUE
);

CREATE TABLE AMB_USUARIOS (
  ID_USUARIO AUTOINCREMENT PRIMARY KEY,
  NOME TEXT(150) NOT NULL,
  USUARIO TEXT(80) NOT NULL,
  SENHA_HASH LONGTEXT NOT NULL,
  PERFIL TEXT(50) NOT NULL,
  ID_PROFISSIONAL LONG,
  ATIVO YESNO DEFAULT TRUE,
  DATA_CRIACAO DATETIME,
  ULTIMO_LOGIN DATETIME
);

CREATE TABLE AMB_PACIENTES (
  ID_PACIENTE AUTOINCREMENT PRIMARY KEY,
  CNS TEXT(30) NOT NULL,
  NOME_PACIENTE TEXT(180) NOT NULL,
  NOME_SOCIAL TEXT(180),
  PRONTUARIO TEXT(50),
  DATA_NASCIMENTO DATETIME,
  TELEFONE TEXT(30),
  OBSERVACAO LONGTEXT,
  DATA_CADASTRO DATETIME,
  ATIVO YESNO DEFAULT TRUE
);

CREATE TABLE AMB_PROFISSIONAIS (
  ID_PROFISSIONAL AUTOINCREMENT PRIMARY KEY,
  NOME TEXT(180) NOT NULL,
  USUARIO_VINCULADO TEXT(80),
  CRM TEXT(30),
  ATIVO YESNO DEFAULT TRUE
);

CREATE TABLE AMB_ESPECIALIDADES (
  ID_ESPECIALIDADE AUTOINCREMENT PRIMARY KEY,
  NOME_ESPECIALIDADE TEXT(120) NOT NULL,
  ATIVO YESNO DEFAULT TRUE
);

CREATE TABLE AMB_PROFISSIONAL_ESPECIALIDADE (
  ID_PROF_ESP AUTOINCREMENT PRIMARY KEY,
  ID_PROFISSIONAL LONG NOT NULL,
  ID_ESPECIALIDADE LONG NOT NULL,
  ATIVO YESNO DEFAULT TRUE
);

CREATE TABLE AMB_SETOR_FILA (
  ID_SETOR AUTOINCREMENT PRIMARY KEY,
  CODIGO_SETOR TEXT(60) NOT NULL,
  NOME_SETOR TEXT(120) NOT NULL,
  ATIVO YESNO DEFAULT TRUE,
  ORDEM_EXIBICAO LONG
);

CREATE TABLE AMB_PRIORIDADES (
  ID_PRIORIDADE AUTOINCREMENT PRIMARY KEY,
  CODIGO_PRIORIDADE TEXT(60) NOT NULL,
  NOME_PRIORIDADE TEXT(120) NOT NULL,
  NIVEL_PRIORIDADE LONG DEFAULT 0,
  ATIVO YESNO DEFAULT TRUE
);

CREATE TABLE AMB_FILA (
  ID_FILA AUTOINCREMENT PRIMARY KEY,
  ID_PACIENTE LONG NOT NULL,
  CNS TEXT(30),
  NOME_PACIENTE TEXT(180),
  NOME_SOCIAL TEXT(180),
  PRONTUARIO TEXT(50),
  DATA_NASCIMENTO DATETIME,

  SETOR_ATUAL TEXT(60) NOT NULL,
  STATUS_ATENDIMENTO TEXT(60) NOT NULL,

  ID_MEDICO_DESTINO LONG,
  NOME_MEDICO_DESTINO TEXT(180),
  ESPECIALIDADE TEXT(120),

  PRIORITARIO YESNO DEFAULT FALSE,
  TIPO_PRIORIDADE TEXT(120),
  OBS_PRIORIDADE LONGTEXT,
  NIVEL_PRIORIDADE LONG DEFAULT 0,

  RETORNO_EXAME YESNO DEFAULT FALSE,
  TIPO_EXAME TEXT(60),
  MOTIVO_PAUSA LONGTEXT,

  DATA_HORA_ENTRADA DATETIME,
  DATA_HORA_CHAMADA DATETIME,
  DATA_HORA_APARECEU DATETIME,
  DATA_HORA_PAUSA DATETIME,
  DATA_HORA_RETORNO DATETIME,
  DATA_HORA_CHECKOUT DATETIME,
  DATA_HORA_ECO_INICIO DATETIME,
  DATA_HORA_ECO_REALIZADO DATETIME,

  ORDEM LONG DEFAULT 0,
  OBSERVACAO_ENCAMINHAMENTO LONGTEXT,
  USUARIO_RESPONSAVEL TEXT(80)
);

CREATE TABLE AMB_CHAMADAS (
  ID_CHAMADA AUTOINCREMENT PRIMARY KEY,
  ID_FILA LONG NOT NULL,
  NOME_PACIENTE TEXT(180),
  SETOR_ATUAL TEXT(60),
  DESTINO TEXT(180),
  PROFISSIONAL TEXT(180),
  ESPECIALIDADE TEXT(120),
  DATA_HORA_CHAMADA DATETIME,
  EXIBIDA YESNO DEFAULT FALSE
);

CREATE TABLE AMB_ATENDIMENTOS (
  ID_ATENDIMENTO AUTOINCREMENT PRIMARY KEY,
  ID_FILA LONG,
  ID_PACIENTE LONG,
  CNS TEXT(30),
  NOME_PACIENTE TEXT(180),
  SETOR TEXT(60),
  STATUS_ATENDIMENTO TEXT(60),
  ID_MEDICO_DESTINO LONG,
  NOME_MEDICO_DESTINO TEXT(180),
  ESPECIALIDADE TEXT(120),
  PRIORITARIO YESNO DEFAULT FALSE,
  TIPO_PRIORIDADE TEXT(120),
  RETORNO_EXAME YESNO DEFAULT FALSE,
  TIPO_EXAME TEXT(60),
  DATA_HORA_ENTRADA DATETIME,
  DATA_HORA_CHAMADA DATETIME,
  DATA_HORA_APARECEU DATETIME,
  DATA_HORA_CHECKOUT DATETIME,
  USUARIO_RESPONSAVEL TEXT(80)
);

CREATE TABLE AMB_CONFIGURACOES (
  ID_CONFIG AUTOINCREMENT PRIMARY KEY,
  CHAVE TEXT(120) NOT NULL,
  VALOR LONGTEXT,
  DESCRICAO LONGTEXT,
  ATIVO YESNO DEFAULT TRUE
);