INSERT INTO AMB_SETOR_FILA (CODIGO_SETOR, NOME_SETOR, ATIVO, ORDEM_EXIBICAO)
VALUES ('ACOLHIMENTO', 'Acolhimento', TRUE, 1);

INSERT INTO AMB_SETOR_FILA (CODIGO_SETOR, NOME_SETOR, ATIVO, ORDEM_EXIBICAO)
VALUES ('ECG', 'Sala de E.C.G.', TRUE, 2);

INSERT INTO AMB_SETOR_FILA (CODIGO_SETOR, NOME_SETOR, ATIVO, ORDEM_EXIBICAO)
VALUES ('MEDICACAO', 'Sala de Medicação', TRUE, 3);

INSERT INTO AMB_SETOR_FILA (CODIGO_SETOR, NOME_SETOR, ATIVO, ORDEM_EXIBICAO)
VALUES ('MEDICO', 'Médico', TRUE, 4);

INSERT INTO AMB_SETOR_FILA (CODIGO_SETOR, NOME_SETOR, ATIVO, ORDEM_EXIBICAO)
VALUES ('CURATIVO', 'Sala de Curativo', TRUE, 5);

INSERT INTO AMB_SETOR_FILA (CODIGO_SETOR, NOME_SETOR, ATIVO, ORDEM_EXIBICAO)
VALUES ('ECO', 'Sala de ECO', TRUE, 6);

INSERT INTO AMB_SETOR_FILA (CODIGO_SETOR, NOME_SETOR, ATIVO, ORDEM_EXIBICAO)
VALUES ('MAPA_CIRURGICO', 'Mapa 24h', TRUE, 7);

INSERT INTO AMB_PRIORIDADES (CODIGO_PRIORIDADE, NOME_PRIORIDADE, NIVEL_PRIORIDADE, ATIVO)
VALUES ('CADEIRANTE', 'Cadeirante', 3, TRUE);

INSERT INTO AMB_PRIORIDADES (CODIGO_PRIORIDADE, NOME_PRIORIDADE, NIVEL_PRIORIDADE, ATIVO)
VALUES ('POS_OPERATORIO', 'Pós-operatório', 3, TRUE);

INSERT INTO AMB_PRIORIDADES (CODIGO_PRIORIDADE, NOME_PRIORIDADE, NIVEL_PRIORIDADE, ATIVO)
VALUES ('POS_ANGIOPLASTIA', 'Pós-angioplastia', 3, TRUE);

INSERT INTO AMB_PRIORIDADES (CODIGO_PRIORIDADE, NOME_PRIORIDADE, NIVEL_PRIORIDADE, ATIVO)
VALUES ('IDOSO', 'Idoso', 2, TRUE);

INSERT INTO AMB_PRIORIDADES (CODIGO_PRIORIDADE, NOME_PRIORIDADE, NIVEL_PRIORIDADE, ATIVO)
VALUES ('GESTANTE', 'Gestante', 2, TRUE);

INSERT INTO AMB_PRIORIDADES (CODIGO_PRIORIDADE, NOME_PRIORIDADE, NIVEL_PRIORIDADE, ATIVO)
VALUES ('DEFICIENCIA', 'Deficiência', 2, TRUE);

INSERT INTO AMB_PRIORIDADES (CODIGO_PRIORIDADE, NOME_PRIORIDADE, NIVEL_PRIORIDADE, ATIVO)
VALUES ('OUTRO', 'Outro', 1, TRUE);

INSERT INTO AMB_CONFIGURACOES (CHAVE, VALOR, DESCRICAO, ATIVO)
VALUES ('TEMPO_EXIBICAO_CHAMADA_MS', '10000', 'Tempo de exibição de cada chamada no painel', TRUE);

INSERT INTO AMB_CONFIGURACOES (CHAVE, VALOR, DESCRICAO, ATIVO)
VALUES ('TEMPO_MINIMO_ATENDIMENTO_SEG', '60', 'Tempo mínimo para liberar finalização de atendimento', TRUE);